# Note: this docker compose stack should only be used for development purposes.
# Do not use it for production deployments. If you want to deploy DOMjudge in
# production with Docker, see https://hub.docker.com/r/domjudge/domserver.
# It is recommended to use `docker compose up` to start this stack. Note, don't
# use sudo or the legacy docker-compose.

services:
  mariadb:
    image: mysql:8.4.3
    environment:
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=domjudge
      - MYSQL_DATABASE=domjudge
    ports:
      # Useful to connect a local MySQL client / GUI
      - 127.0.0.1:13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - database:/var/lib/mysql
      # If you have a database dump, you can mount it here
      # - ./database.sql.gz:/docker-entrypoint-initdb.d/database.sql.gz
  domjudge:
    image: deltacs/seminar-domjudge-contributor:8.3.1
    hostname: domjudge-contributor
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - .:${PWD}:cached
      - /chroot
    links:
      - mariadb:mariadb
    ports:
      - 12345:80
    privileged: true
    working_dir: ${PWD}
    environment:
      - PROJECT_DIR=${PWD}

volumes:
  database:
